// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactNative from "react-native";
import * as ApolloClient__React_Hooks_UseSubscription from "reason-apollo-client/src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseSubscription.bs.js";

var Raw = {};

var query = (require("@apollo/client").gql`
  subscription SorryItsNotASubscriptionForTodos  {
    siteStatisticsUpdated  {
      __typename
      currentVisitorsOnline
    }
  }
`);

function parse(value) {
  var value$1 = value.siteStatisticsUpdated;
  return {
          siteStatisticsUpdated: !(value$1 == null) ? ({
                __typename: value$1.__typename,
                currentVisitorsOnline: value$1.currentVisitorsOnline
              }) : undefined
        };
}

function serialize(value) {
  var value$1 = value.siteStatisticsUpdated;
  var siteStatisticsUpdated;
  if (value$1 !== undefined) {
    var value$2 = value$1.currentVisitorsOnline;
    var value$3 = value$1.__typename;
    siteStatisticsUpdated = {
      __typename: value$3,
      currentVisitorsOnline: value$2
    };
  } else {
    siteStatisticsUpdated = null;
  }
  return {
          siteStatisticsUpdated: siteStatisticsUpdated
        };
}

function serializeVariables(param) {
  
}

function makeVariables(param) {
  
}

function makeDefaultVariables(param) {
  
}

var SorryItsNotASubscriptionForTodos_inner = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables
};

var include = ApolloClient__React_Hooks_UseSubscription.Extend({
      query: query,
      Raw: Raw,
      parse: parse,
      serialize: serialize,
      serializeVariables: serializeVariables
    });

var use = include.use;

var SorryItsNotASubscriptionForTodos = {
  SorryItsNotASubscriptionForTodos_inner: SorryItsNotASubscriptionForTodos_inner,
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables,
  use: use
};

function Subscription(Props) {
  var _ignoredForExample = Curry._7(use, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var match = _ignoredForExample.data;
  var tmp;
  if (match !== undefined) {
    var match$1 = match.siteStatisticsUpdated;
    tmp = match$1 !== undefined ? React.createElement(ReactNative.Text, {
            children: "There are " + (String(match$1.currentVisitorsOnline) + " visitors online")
          }) : null;
  } else {
    tmp = null;
  }
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: "[ Not functional, but the examples are still valid ]"
                }), tmp);
}

var make = Subscription;

export {
  SorryItsNotASubscriptionForTodos ,
  make ,
  
}
/* query Not a pure module */
